[project]
name = "tts-flask-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dashscope>=1.25.2",
    "flask>=3.1.2",
    "flask-cors>=5.0.0",
    "python-dotenv>=1.2.1",
]
